# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4afc30a19e4c95aa83a2ec0eb5b3fc6a80b8ec03970b0312646bd3d4a65636663484b840ac9de6fd5d667e35b84baa889977380a6ee61cff9355eed95d5bf3f9

test:
  secret_key_base: 129a3a462c79a3974bdfaca0734c903ab7bf125740a00b826eadb8eb0b92fd67387908470ff4b64c5ba59dcb9b7107a5f25f84566819aaa1878bca1878481bcf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
